### ISSUE TITLE
Eslint w/ Eslint-plugin-yaml: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by mwallace72** [aminya/eslint-plugin-yaml#67]
Linting a legitimate K8S ingress YAML file:

`front-end-ingress.yaml`:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-ingress
  namespace: space
spec:
  rules:
  - host: hostname.com
    http:
      paths:
      - backend:
          serviceName: service
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-ingress-nonlive
  namespace: space
spec:
  rules:
  - host: hostname-nonlive.com
    http:
      paths:
      - backend:
          serviceName: service-b
          servicePort: 80
```

Results in `TypeError: Cannot read property 'buffer' of undefined`.
Versions:
* Node v12.14.1
* Eslint: 6.8.0 
* Eslint-plugin-yaml: 0.3.0 

Upgrading plugin to latest `0.4.2` did not address issue.
